repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.3
  hooks:
    - id: ruff
      files: ^api/.*\.py$
      exclude: ^api/migrations/env\.py$
      args: [--fix]      
    - id: ruff-format
      files: ^api/.*\.py$