repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.3
  hooks:
    - id: ruff
      files: ^api/.*\.py$
      exclude: ^api/migrations/env\.py$
      args: [--fix]      
    - id: ruff-format
      files: ^api/.*\.py$
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.14.1
  hooks:  
    - id: mypy      
      additional_dependencies: [python-dateutil==2.9.0.post0]